apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-project
  labels:
    app: template-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-project
  template:
    metadata:
      labels:
        app: template-project
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
    spec:
      containers:
        - name: template-project
          image: template-project
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: wallet-config-volume
              mountPath: /workspace/config
      volumes:
        - name: wallet-config-volume
          configMap:
            name: wallet-config
