name: Tests and Linting

on:
  push:
#    branches-ignore:
#      - main
#      - develop

jobs:
  test:
    name: Run Gradle Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Run Gradle tests
        run: |
          chmod +x gradlew
          ./gradlew test

  static-scan:
    name: Static Vulnerability Scan
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

  commit-lint:
    name: Run Commitlint
    runs-on: ubuntu-22.04
    steps:
      - name: Run Commitlint
        uses: wagoid/commitlint-github-action@v5

  code-linting:
    name: Run Code Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Run Gradle linting
        run: |
          chmod +x gradlew
          ./gradlew checkstyleMain checkstyleTest

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest --no-daemon

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest --no-daemon

      - name: Upload lint reports
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            build/reports/checkstyle
            build/reports/pmd
            build/reports/spotbugs

  k8s-validate:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-22.04
    steps:
      - name: Setup tools
        uses: alexellis/setup-arkade@v3
      - name: Install tools
        uses: alexellis/arkade-get@master
        with:
          kustomize: latest
          kubeconform: latest
      - name: Validate Kubernetes manifests
        run: |
          kustomize build k8s | kubeconform --strict -